### PR TITLE
Revert "Aligning event2rdf with ontology (#10)"

### PR DESCRIPTION
**Pull request by cecton**
This reverts commit 93624cb9b7f83320ad92f1928d808865f991c9d5.

The main reason for that revert is because I badly reviewed it and there
are some inconsistencies that breaks the work done by @fr0gs.

Examples:

```diff
-                container_node.add(DOCKCONTAINER.label, Literal("%s=%s" % (label, value)))
+                container_node.add(DOCKEVENT.networkLabel, Literal("%s=%s" % (label, value)))
```

A container label is not a network label.

```diff
-            container_node.add(DOCKCONTAINER.id, Literal(container["Id"]))
-            container_node.add(DOCKCONTAINER.name, Literal(container["Name"]))
+            container_node.add(DOCKEVENT.networkId, Literal(container["Id"]))
+            container_node.add(DOCKEVENT.networkName, Literal(container["Name"]))
```

They are container name and id, not network name or id.

@earthquakesan I invite you to accept this PR request for now to allow @fr0gs to continue his work on some other services and make another PR later that will fix all these issues. The work is not lost, it is just put temporary aside.

Thanks for your understanding

### CODE REVIEW

**Review by fr0gs — APPROVED** [review]
Hello, yes, container url's do not represent the information needed and are misleading. Please adapt them.

**Comment by earthquakesan** [comment]
Hi @cecton!

I don't think that reverting commit is a good idea. Better keep both triples generated, just add few lines @fr0gs needs at the moment. This way it will be also easier for @fr0gs to migrate his code later. And after that we can remove triples, which are not aligned with the ontology.

**Comment by earthquakesan** [comment]
Ah, sorry, I seemed to confuse containerId with networkId, accept this pull request, I will make another one.

**Comment by earthquakesan** [comment]
Can you revert only event2rdf.py? Reverting everything will get the changes in ontology lost.

**Comment by cecton** [comment]
Sure

**Comment by earthquakesan** [comment]
thanks

**Comment by cecton** [comment]
Done. Approved? 👍

**Comment by earthquakesan** [comment]
Ok, I will keep the triples @fr0gs need there and add the correct ones as well. I will also make an issue with milestone as we have to migrate to correct ontology ASAP. @fr0gs two weeks will be enough time?

**Comment by fr0gs** [comment]
If the old URLs are kept now and in two weeks time are going to change again, I'd rather wait two weeks until the final values are established. Otherwise I will have to keep changing my queries. 

One microservice on **mu-bde-logging** depends on the result of querying the triplestore for container events, the rest is already implemented assuming those queries returned the expected values.

**Comment by cecton** [comment]
Well I think for now it's more on @fr0gs side to see if he can keep going or not but at least he will be able to. So let's merge this for now.

**Comment by cecton** [comment]
I include @asjongers to the conversation because his branch here that is going to be merged will need adaptation when the ontology will change:  https://github.com/big-data-europe/mu-init-daemon-service/commits/logger-healthchecks

**Pull request merged**
