### PR TITLE
Added DockAction prefixes that swarm-logger was not taking into account

### PR DESCRIPTION
**Pull request by fr0gs**

### CODE REVIEW

**Comment by cecton** [comment]
I don't see the point of this PR. Are these prefixed names used somewhere?

**Comment by fr0gs** [comment]
If they are not added the swarm-logger throws exception, although not crashing.

**Comment by cecton** [comment]
Ok, can you paste the traceback in the description of the issue? Also amend your commit and state it a bit more clearly:

> Fixed: added missing prefixed name

(So I know it fixes something and that something was missing)

**Comment by fr0gs** [comment]
```sh
swarm-logger_1        | ERROR:muswarmlogger.events:An error occurred
swarm-logger_1        | Traceback (most recent call last):
swarm-logger_1        |   File "/src/muswarmlogger/events.py", line 98, in send_event
swarm-logger_1        |     raise exc
swarm-logger_1        |   File "/src/muswarmlogger/loggers/sparql/events.py", line 53, in store_events
swarm-logger_1        |     (DockEvent.action, getattr(DockEventActions, event_action_type)))
swarm-logger_1        | AttributeError: type object 'DockEventActions' has no attribute 'kill'
swarm-logger_1        | ERROR:muswarmlogger.events:An error occurred
swarm-logger_1        | Traceback (most recent call last):
swarm-logger_1        |   File "/src/muswarmlogger/events.py", line 98, in send_event
swarm-logger_1        |     raise exc
swarm-logger_1        |   File "/src/muswarmlogger/loggers/sparql/events.py", line 53, in store_events
swarm-logger_1        |     (DockEvent.action, getattr(DockEventActions, event_action_type)))
swarm-logger_1        | AttributeError: type object 'DockEventActions' has no attribute 'kill'
swarm-logger_1        | ERROR:muswarmlogger.events:An error occurred
swarm-logger_1        | Traceback (most recent call last):
swarm-logger_1        |   File "/src/muswarmlogger/events.py", line 98, in send_event
swarm-logger_1        |     raise exc
swarm-logger_1        |   File "/src/muswarmlogger/loggers/sparql/events.py", line 53, in store_events
swarm-logger_1        |     (DockEvent.action, getattr(DockEventActions, event_action_type)))
swarm-logger_1        | AttributeError: type object 'DockEventActions' has no attribute 'stop'
```

**Comment by cecton** [comment]
@fr0gs ahh now I see. Maybe you can completely get rid of the `getattr(DockEventActions, event_action_type)` and use `RDF("dockeventactions:%s" % event_action_type)` instead? It would be nice to have a shortcut for this on aiosparql so we could do `DockEventActions + event_action_type`. What do you think?

**Comment by fr0gs** [comment]
I like the way it is. Using the `RDF("dockeventactions:%s" % event_action_type)` way does not enforce knowing exactly which actions the logger understands.

**Review by cecton — APPROVED** [review]
Fair enough

**Pull request merged**
